version: '3.7'

volumes:
  redis: {}

services:
  redis:
    image: redis:alpine
    volumes:
      - redis:/data

  api:
    build: .
    depends_on:
      - redis
    environment:
      OA_REDIS_MAIN_URL: redis://redis:6379/0
      OA_REDIS_QUEUE_URL: redis://redis:6379/1
    env_file:
      - ./.secrets.env
